global:
  application_name: Arimo-IoT
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: arimo
  repository: null
  sc: git
  workspace_type: Application
