branch-defaults:
  master:
    environment: TEST
global:
  application_name: ArimoIoTDataAdmin-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: arimo
  repository: null
  sc: null
  workspace_type: Application
