branch-defaults:
  ACCDC:
    environment: PanaAP-JP-FC-ACCDC
    group_suffix: null
  master:
    environment: TEST
global:
  application_name: Arimo-IoT
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: accdc
  repository: null
  sc: null
  workspace_type: Application
