branch-defaults:
  master:
    environment: TEST

global:
  application_name: Arimo-IoT
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: arimo
  repository: null
  sc: null
  workspace_type: Application
