branch-defaults:
  main:
    environment: Aitomatic-PredMaint
global:
  application_name: Aitomatic-PredMaint
  branch: null
  default_ec2_keyname: pred-maint
  default_platform: Python 3.8
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
