installer:
  installer_root: /opt/arimo-installer
  data_root: /opt/arimo-data

env:
  DOCKER_PULL_METHOD: pull
  YARN_MASTER_NODE: ${master_node}
  YARN_NODEMANAGER_RESOURCE_MEMORY_MB: ${yarn_worker_memory}
  YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: 512

provisioner:
  yarn:
    master:
      init_script: s3://arimo-bai-clusters/custom_provisioner/ccpm/yarn-deps.sh
    slave:
      init_script: s3://arimo-bai-clusters/custom_provisioner/ccpm/yarn-deps.sh

hosts:
  slave:
    ip: localhost
    roles:
      yarn:
        - slave
